[server]
maxUploadSize = 200
maxMessageSize = 200
enableXsrfProtection = false
enableCORS = false
runOnSave = true
port = 8501
address = "localhost"

[browser]
serverAddress = "localhost"
serverPort = 8501
gatherUsageStats = false

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = true

[runner]
fastReruns = true
